### ISSUE TITLE
`Repl` and `Commands` class doesn't handle relative path.

### ISSUE THREAD

**Issue by abir0** [DavinderJolly/bright-bluefins#29]
Some [commands](https://github.com/DavinderJolly/bright-bluefins/blob/main/main/commands.py) don't work with the path relative to the REPL, it just works with the path relative to the python file system.
For example:

`F:\Projects\bright-bluefins>type main\commands.py`

This should print the contents of the `commands.py`, but it gives,

`FileNotFoundError: [Errno 2] No such file or directory: 'main\\commands.py'`.

These commands should use the `current_path` of the REPL to correctly use the relative path.
Before adding new commands please consider this issue. @DavinderJolly @Anonymous390 @dumdoo

**Comment by DavinderJolly** [comment]
# @abir0 
### can you list me the commands that are broken?
#### will try to fix  them
